  
  fail_fast: true
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.50
    hooks:
      - id: checkov
        verbose: false
        args: [--soft-fail]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: "examples/"
      - id: terraform_docs
  
  

